### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Winswins22** [QqWwEe123123123/hackathon#6]
- [ ] Create HTML/CSS MainBrowserSocialBrowsingPage
- [ ] Finish HTML/CSS/JS for MessengerPage
- [ ] Finish polishing MainIntroductionPage
- [ ] Fix up AboutPage
- [ ] Add maps and link shortener to messagingPage

**servers:**
- [ ] fix forgot password
- [ ] create chat system
- [ ] **ROUTE ALL LINK THROUGHT SERVER**
